version: 2.1

jobs:
  build:
    docker:
      - image: node:18.15
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - challenge-cache-{{ checksum "pom.xml" }}
          - challenge-cache- 

      - run:
          name: "install dependencies"
          command: |
            npm install -g npm@9.6.7
            apt-get update && apt-get install -y default-jre
            npm install 


      - save_cache:
          paths:
            ~/.m2/repository
          key: challenge-cache-{{ checksum "package.json" }}

      - run:
          name: "run test"
          command: npm start

      - run:
          name: "Generate allure reports"
          command: "allure gerenate"

      - save_cache:
          key: allure-history-{{ checksum "allure-history.tar.gz" }}
          paths:
              - ./allure-history.tar.gz

      - store_artifacts:
          path: /tmp/test-reports
          destination: test-reports


